name: MSStore CLI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msstore-cli@v1.1
    - run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --sellerId ${{ secrets.SELLER_ID }} --clientId ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
    - run: msstore apps list
    
    - run: msstore submission updateMetadata 9NP0T3QQXL70 @FF/updated_metadata.json

    - run: msstore submission update 9NP0T3QQXL70
    - run: msstore submission publish 9NP0T3QQXL70
