name: MSStore CLI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msstore-cli@v1.1
    - run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --sellerId ${{ secrets.SELLER_ID }} --clientId ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
    - run: msstore apps list
    - name: Debug metadata.json
    - run: |
        echo "Checking if metadata.json exists..."
        ls -l FF/metadata.json || echo "File not found!"
        echo
        echo "First few lines of metadata.json:"
        head -n 20 FF/metadata.json || echo "Cannot read file!"
        echo
        echo "Validating JSON format..."
        cat FF/metadata.json | jq . || echo "Invalid JSON or jq not installed"  
    - run: msstore submission updateMetadata 9NP0T3QQXL70 FF/metadata.json
    - run: msstore submission update 9NP0T3QQXL70
    - run: msstore submission publish 9NP0T3QQXL70
    
