name: MSStore CLI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msstore-cli@v1.1
    - run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --sellerId ${{ secrets.SELLER_ID }} --clientId ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
    - run: msstore apps list
    - run: msstore submission updateMetadata 9NP0T3QQXL70 "{
  "ApplicationCategory": "HealthAndFitness",
  "Pricing": {
    "TrialPeriod": "TrialNeverExpires",
    "MarketSpecificPricings": {
      "LB": "NotAvailable",
      "EH": "NotAvailable"
    },
    "PriceId": "Free",
    "IsAdvancedPricingModel": true
  },
  "Visibility": "Public",
  "TargetPublishMode": "Immediate",
  "TargetPublishDate": "1601-01-01T00:00:00Z",
  "Listings": {
    "en": {
      "BaseListing": {
        "Keywords": [],
        "privacyPolicy" : "pp1",
        "Description": "from store cli - en",
        "Features": [],
        "ReleaseNotes": "",
        "Images": [
          {
            "FileName": "Screenshot1.png",
            "FileStatus": "Uploaded",
            "Id": "1152922700019982211",
            "ImageType": "Screenshot"
          },
          {
            "FileName": "Screenshot2.png",
            "FileStatus": "Uploaded",
            "Id": "1152922700019982125",
            "ImageType": "Screenshot"
          },
          {
            "FileName": "Screenshot3.png",
            "FileStatus": "Uploaded",
            "Id": "1152922700019982733",
            "ImageType": "Screenshot"
          },
          {
            "FileName": "zeeconvert-resizer.png",
            "FileStatus": "Uploaded",
            "Id": "1152922700019982126",
            "ImageType": "Icon"
          },
          {
            "FileName": "zeeconvert-resizer (1).png",
            "FileStatus": "Uploaded",
            "Id": "1152922700019982212",
            "ImageType": "StoreLogo9x16"
          }
        ],
        "RecommendedHardware": [],
        "MinimumHardware": [],
        "Title": "FitnessFuel"
      },
      "PlatformOverrides": {}
    },
    "fr": {
      "BaseListing": {
        "Keywords": [],
        "privacyPolicy" : "pp2",
        "Description": "test store cli - fr",
        "Features": [],
        "ReleaseNotes": "",
        "Images": [
          {
            "FileName": "Screenshot1.png",
            "FileStatus": "Uploaded",
            "Id": "1152922700019982211",
            "ImageType": "Screenshot"
          }
        ],
        "RecommendedHardware": [],
        "MinimumHardware": [],
        "Title": "FitnessFuel"
      },
      "PlatformOverrides": {}
    }
    
  },
  "HardwarePreferences": [],
  "AutomaticBackupEnabled": false,
  "CanInstallOnRemovableMedia": false,
  "IsGameDvrEnabled": false,
  "GamingOptions": [
    {
      "Genres": [],
      "IsLocalMultiplayer": false,
      "IsLocalCooperative": false,
      "IsOnlineMultiplayer": false,
      "IsOnlineCooperative": false,
      "IsBroadcastingPrivilegeGranted": true,
      "IsCrossPlayEnabled": false,
      "KinectDataForExternal": "Disabled"
    }
  ],
  "HasExternalInAppProducts": false,
  "MeetAccessibilityGuidelines": false,
  "ApplicationPackages": [
    {
      "FileName": "pkota.FitnessFuel_1.0.2.0_x86__4fxr7wcjkzrjg_1.msix",
      "FileStatus": "PendingDelete",
      "Id": "2000000000086830858",
      "Version": "1.0.2.0",
      "Architecture": "neutral",
      "Languages": [
        "en-US"
      ],
      "Capabilities": [
        "runFullTrust"
      ],
      "MinimumDirectXVersion": "None",
      "MinimumSystemRam": "None"
    }
  ],
  "AllowMicrosoftDecideAppAvailabilityToFutureDeviceFamilies": false,
  "AllowTargetFutureDeviceFamilies": {
    "Desktop": true,
    "Mobile": false,
    "Xbox": false,
    "Team": false,
    "Holographic": true
  },
  "Trailers": []
}"
    - run: msstore submission update 9NP0T3QQXL70
    - run: msstore submission publish 9NP0T3QQXL70
