name: MSStore CLI
on:
      workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msstore-cli@v1.1
    - run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --sellerId ${{ secrets.SELLER_ID }} --clientId ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
    - run: msstore apps list
    - name: Update Metadata and Publish
      shell: pwsh
      run: |
          $json = msstore submission get 9NP0T3QQXL70 | ConvertFrom-Json -AsHashtable
          $json.Listings.'en-us'.BaseListing.Description = 'From GitHub action'
          $payload = $json | ConvertTo-Json -Depth 100 -Compress
          msstore submission updateMetadata 9NP0T3QQXL70 "$payload" -v
          msstore submission publish 9NP0T3QQXL70
        
  #  - run: msstore publish -i FF/app -id 9NP0T3QQXL70
